classdef BehaviorCommand
    % BehaviorCommand  Команда поведенческого планировщика для цели.

    methods (Static)
        function command = create(args)
            arguments
                args.BehaviorMode (1, 1) BehaviorMode
                args.DesiredPosition (1, 3) double = [nan, nan, nan]
                args.DesiredHeading (1, 1) double = nan
                args.DesiredSpeed (1, 1) double = nan
                args.DesiredAltitude (1, 1) double = nan
                args.DesiredVerticalSpeed (1, 1) double = nan
                args.HoldTime (1, 1) double = 5
                args.Priority (1, 1) double = 1
                args.Reason (1, :) char = ''
            end

            command = struct( ...
                'BehaviorMode', args.BehaviorMode, ...
                'DesiredPosition', args.DesiredPosition, ...
                'DesiredHeading', args.DesiredHeading, ...
                'DesiredSpeed', args.DesiredSpeed, ...
                'DesiredAltitude', args.DesiredAltitude, ...
                'DesiredVerticalSpeed', args.DesiredVerticalSpeed, ...
                'HoldTime', args.HoldTime, ...
                'Priority', args.Priority, ...
                'Reason', args.Reason);
        end

        function command = empty()
            command = BehaviorCommand.create( ...
                'BehaviorMode', BehaviorMode.Cruise, ...
                'DesiredPosition', [nan, nan, nan], ...
                'DesiredHeading', nan, ...
                'DesiredSpeed', nan, ...
                'DesiredAltitude', nan, ...
                'DesiredVerticalSpeed', nan, ...
                'HoldTime', 0, ...
                'Priority', 0, ...
                'Reason', '');
        end

        function tf = isActive(command)
            tf = isstruct(command) && ...
                isfield(command, 'BehaviorMode') && ...
                isfield(command, 'HoldTime') && ...
                command.HoldTime > 0;
        end
    end
end
