classdef MissionCommand
    % MissionCommand  Команда миссионного планировщика для цели.

    methods (Static)
        function command = create(args)
            arguments
                args.MissionType (1, 1) MissionType
                args.MissionRoute (:, 3) double
                args.DesiredMissionSpeed (1, 1) double = nan
                args.DesiredMissionAltitude (1, 1) double = nan
                args.MissionHoldTime (1, 1) double = 20
                args.MissionPriority (1, 1) double = 1
                args.MissionReason (1, :) char = ''
                args.MissionStartTime (1, 1) double = 0
                args.Status (1, 1) MissionStatus = MissionStatus.Created
            end

            route = args.MissionRoute;
            if size(route, 1) < 1
                route = [nan, nan, nan];
            end

            currentIndex = 1;
            currentWaypoint = route(currentIndex, :);
            nextWaypoint = MissionCommand.nextWaypointAt(route, currentIndex);
            totalCount = size(route, 1);

            command = struct( ...
                'MissionType', args.MissionType, ...
                'MissionRoute', route, ...
                'CurrentWaypointIndex', currentIndex, ...
                'CurrentWaypoint', currentWaypoint, ...
                'NextWaypoint', nextWaypoint, ...
                'DesiredMissionSpeed', args.DesiredMissionSpeed, ...
                'DesiredMissionAltitude', args.DesiredMissionAltitude, ...
                'MissionStartTime', args.MissionStartTime, ...
                'MissionHoldTime', args.MissionHoldTime, ...
                'MissionPriority', args.MissionPriority, ...
                'MissionReason', args.MissionReason, ...
                'IsMissionComplete', false, ...
                'Status', args.Status, ...
                'PreviousStatus', args.Status, ...
                'StatusStartTime', args.MissionStartTime, ...
                'StatusTime', 0, ...
                'CompletionReason', '', ...
                'CancelReason', '', ...
                'Progress', 0, ...
                'DistanceToCurrentWaypoint', inf, ...
                'ReachedWaypointCount', 0, ...
                'TotalWaypointCount', totalCount);
        end

        function command = empty()
            command = MissionCommand.create( ...
                'MissionType', MissionType.Idle, ...
                'MissionRoute', [nan, nan, nan], ...
                'DesiredMissionSpeed', nan, ...
                'DesiredMissionAltitude', nan, ...
                'MissionHoldTime', 0, ...
                'MissionPriority', 0, ...
                'MissionReason', '', ...
                'Status', MissionStatus.Cancelled);
        end

        function tf = isActive(command)
            tf = isstruct(command) && ...
                isfield(command, 'MissionType') && ...
                isfield(command, 'MissionHoldTime') && ...
                command.MissionHoldTime > 0 && ...
                command.MissionType ~= MissionType.Idle;
        end

        function command = advanceWaypoint(command, position, threshold)
            if nargin < 3
                threshold = 20;
            end

            if command.IsMissionComplete
                return;
            end

            if norm(position(1:2) - command.CurrentWaypoint(1:2)) > threshold
                return;
            end

            command.ReachedWaypointCount = command.ReachedWaypointCount + 1;
            nextIndex = command.CurrentWaypointIndex + 1;
            if nextIndex > size(command.MissionRoute, 1)
                command.IsMissionComplete = true;
                command.NextWaypoint = [nan, nan, nan];
                command.Progress = 1;
                return;
            end

            command.CurrentWaypointIndex = nextIndex;
            command.CurrentWaypoint = command.MissionRoute(nextIndex, :);
            command.NextWaypoint = MissionCommand.nextWaypointAt( ...
                command.MissionRoute, nextIndex);
            command.Progress = min(1, command.ReachedWaypointCount / max(command.TotalWaypointCount, 1));
        end

        function waypoint = nextWaypointAt(route, index)
            if index < size(route, 1)
                waypoint = route(index + 1, :);
            else
                waypoint = [nan, nan, nan];
            end
        end
    end
end
