classdef QuadcopterMissionPlanner
    % QuadcopterMissionPlanner  Миссии инспекции по Environment.InspectionZones.

    methods (Static)
        function command = createMission(target, environment)
            stream = RandStream('mt19937ar', 'Seed', round(environment.RandomSeed + target.ID));
            [zone, zoneIndex] = InspectionRouteBuilder.selectInspectionZone( ...
                environment, target.Position, stream);

            if zoneIndex < 1
                command = QuadcopterMissionPlanner.fallbackMission(target, environment);
                return;
            end

            [route, ~] = InspectionRouteBuilder.buildInspectionRoute( ...
                zone, environment, stream, target.Position);
            if size(route, 1) < 3
                command = QuadcopterMissionPlanner.fallbackMission(target, environment);
                return;
            end

            holdTime = MissionTypeCatalog.minimumHoldTime(target.Type);
            moveSpeed = 5 + 7 * stream.rand();
            legCount = max(size(route, 1) - 1, 1);

            command = MissionCommand.create( ...
                'MissionType', MissionType.InspectArea, ...
                'MissionRoute', route, ...
                'DesiredMissionSpeed', moveSpeed, ...
                'DesiredMissionAltitude', route(1, 3), ...
                'MissionHoldTime', holdTime, ...
                'MissionPriority', 1, ...
                'MissionReason', 'Quadcopter inspection zone route', ...
                'MissionStartTime', target.MissionTime);

            command = QuadcopterMissionPlanner.attachInspectionFields(command, zoneIndex, stream, legCount);
        end
    end

    methods (Static, Access = private)
        function command = attachInspectionFields(command, zoneIndex, stream, legCount)
            command.InspectionZoneIndex = zoneIndex;
            command.InspectionPhase = InspectionPhase.MoveToPoint;
            command.InspectionHoverTime = 0;
            command.InspectionHoverElapsed = 0;
            command.InspectionHoverAltitude = nan;
            command.InspectionHoverSpeed = nan;
            command.InspectionHoverPosition = [nan, nan, nan];
            command.InspectionPhaseAltitude = nan;
            command.InspectionAdjustFlags = stream.rand(legCount, 1) < 0.2;
            command.InspectionAdjustDelta = (10 + 20 * stream.rand(legCount, 1)) .* ...
                (2 * (stream.rand(legCount, 1) > 0.5) - 1);
        end

        function command = fallbackMission(target, environment)
            zoneInfo = Environment.findNearestInspectionZone(environment, target.Position);

            if zoneInfo.Index > 0
                stream = RandStream('mt19937ar', 'Seed', round(environment.RandomSeed + target.ID + 53));
                zone = zoneInfo.Zone;
                [route, ~] = InspectionRouteBuilder.buildInspectionRoute( ...
                    zone, environment, stream, target.Position);
                command = MissionCommand.create( ...
                    'MissionType', MissionType.InspectArea, ...
                    'MissionRoute', route, ...
                    'DesiredMissionSpeed', 8, ...
                    'DesiredMissionAltitude', route(1, 3), ...
                    'MissionHoldTime', MissionTypeCatalog.minimumHoldTime(target.Type), ...
                    'MissionPriority', 1, ...
                    'MissionReason', 'Quadcopter inspection zone route', ...
                    'MissionStartTime', target.MissionTime);
                command = QuadcopterMissionPlanner.attachInspectionFields( ...
                    command, zoneInfo.Index, stream, max(size(route, 1) - 1, 1));
                return;
            end

            command = MissionCommand.create( ...
                'MissionType', MissionType.InspectArea, ...
                'MissionRoute', target.Position, ...
                'DesiredMissionSpeed', 8, ...
                'DesiredMissionAltitude', target.Position(3), ...
                'MissionHoldTime', MissionTypeCatalog.minimumHoldTime(target.Type), ...
                'MissionPriority', 1, ...
                'MissionReason', 'Quadcopter inspection fallback', ...
                'MissionStartTime', target.MissionTime);
            command = QuadcopterMissionPlanner.attachInspectionFields(command, 0, ...
                RandStream('mt19937ar', 'Seed', 1), 1);
        end
    end
end
